/* ========================================================================
 * Chess C engine runtime tables: Zobrist keys, attack bitmasks, ray
 * tables. All initialised on first call to chess_init_tables() and
 * used thereafter by _chess_movegen_c.c and _chess_rule_search.c.
 *
 * Zobrist keys are generated by a fixed-seed SplitMix64 — self-contained,
 * not compatible with the Python np.random seed. The C search uses
 * its own TT with these keys; no Python round-trip depends on them.
 * ======================================================================= */

#include "_nnue_accel_header.h"
#include "_chess_position.h"

/* Global tables declared in _chess_position.h */
uint64_t g_chess_z_piece[7][2][64];
uint64_t g_chess_z_side;
uint64_t g_chess_z_castling[16];
uint64_t g_chess_z_ep_file[8];
int      g_chess_zobrist_ready = 0;

uint64_t g_chess_knight_attacks[64];
uint64_t g_chess_king_attacks[64];
uint64_t g_chess_pawn_attacks[2][64];

int8_t g_chess_rays[8][64][8];
int8_t g_chess_ray_len[8][64];

/* ---- SplitMix64 PRNG for Zobrist seeding ------------------------------ */
static uint64_t splitmix64_next(uint64_t *state) {
    uint64_t z = (*state += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

/* ---- Direction vectors ------------------------------------------------ */
/* Rook = 4 orthogonal, Bishop = 4 diagonal. Stored as (dr, df) pairs
 * at indices 0..3 (rook) and 4..7 (bishop). Combined they form the
 * queen dirs. */
static const int CHESS_DIRS[8][2] = {
    { 1,  0}, {-1,  0}, { 0,  1}, { 0, -1},   /* rook  0..3 */
    { 1,  1}, { 1, -1}, {-1,  1}, {-1, -1},   /* bishop 4..7 */
};

static const int KNIGHT_OFFS[8][2] = {
    { 2,  1}, { 2, -1}, {-2,  1}, {-2, -1},
    { 1,  2}, { 1, -2}, {-1,  2}, {-1, -2},
};

static const int KING_OFFS[8][2] = {
    { 1,  0}, {-1,  0}, { 0,  1}, { 0, -1},
    { 1,  1}, { 1, -1}, {-1,  1}, {-1, -1},
};

/* ---- Initialisation --------------------------------------------------- */

void chess_init_tables(void) {
    if (g_chess_zobrist_ready) return;

    /* Zobrist keys. Fixed seed so runs are reproducible. */
    uint64_t state = 0xC0FFEECAFEBABEULL;
    for (int pt = 0; pt < 7; pt++) {
        for (int c = 0; c < 2; c++) {
            for (int sq = 0; sq < 64; sq++) {
                g_chess_z_piece[pt][c][sq] = splitmix64_next(&state);
            }
        }
    }
    g_chess_z_side = splitmix64_next(&state);
    for (int i = 0; i < 16; i++) {
        g_chess_z_castling[i] = splitmix64_next(&state);
    }
    for (int f = 0; f < 8; f++) {
        g_chess_z_ep_file[f] = splitmix64_next(&state);
    }

    /* Knight attacks */
    for (int sq = 0; sq < 64; sq++) {
        int r = sq >> 3;
        int f = sq & 7;
        uint64_t bb = 0;
        for (int k = 0; k < 8; k++) {
            int nr = r + KNIGHT_OFFS[k][0];
            int nf = f + KNIGHT_OFFS[k][1];
            if (nr >= 0 && nr < 8 && nf >= 0 && nf < 8) {
                bb |= (uint64_t)1 << ((nr << 3) + nf);
            }
        }
        g_chess_knight_attacks[sq] = bb;
    }

    /* King attacks */
    for (int sq = 0; sq < 64; sq++) {
        int r = sq >> 3;
        int f = sq & 7;
        uint64_t bb = 0;
        for (int k = 0; k < 8; k++) {
            int nr = r + KING_OFFS[k][0];
            int nf = f + KING_OFFS[k][1];
            if (nr >= 0 && nr < 8 && nf >= 0 && nf < 8) {
                bb |= (uint64_t)1 << ((nr << 3) + nf);
            }
        }
        g_chess_king_attacks[sq] = bb;
    }

    /* Pawn attacks — [color][sq] gives the squares the pawn attacks
     * (forward-left and forward-right from the pawn's perspective). */
    for (int sq = 0; sq < 64; sq++) {
        int r = sq >> 3;
        int f = sq & 7;
        uint64_t wb = 0, bb = 0;
        if (r + 1 < 8) {
            if (f - 1 >= 0) wb |= (uint64_t)1 << (((r + 1) << 3) + (f - 1));
            if (f + 1 < 8) wb |= (uint64_t)1 << (((r + 1) << 3) + (f + 1));
        }
        if (r - 1 >= 0) {
            if (f - 1 >= 0) bb |= (uint64_t)1 << (((r - 1) << 3) + (f - 1));
            if (f + 1 < 8) bb |= (uint64_t)1 << (((r - 1) << 3) + (f + 1));
        }
        g_chess_pawn_attacks[0][sq] = wb;
        g_chess_pawn_attacks[1][sq] = bb;
    }

    /* Slider rays: for each direction (0..7) and each starting square,
     * list the reachable squares in order. g_chess_ray_len[d][sq] is
     * the number of valid squares in g_chess_rays[d][sq]. */
    for (int d = 0; d < 8; d++) {
        int dr = CHESS_DIRS[d][0];
        int df = CHESS_DIRS[d][1];
        for (int sq = 0; sq < 64; sq++) {
            int r = sq >> 3;
            int f = sq & 7;
            int n = 0;
            int cr = r + dr;
            int cf = f + df;
            while (cr >= 0 && cr < 8 && cf >= 0 && cf < 8 && n < 8) {
                g_chess_rays[d][sq][n++] = (int8_t)((cr << 3) + cf);
                cr += dr;
                cf += df;
            }
            g_chess_ray_len[d][sq] = (int8_t)n;
        }
    }

    g_chess_zobrist_ready = 1;
}
