#include "_nnue_accel_header.h"
#include "_accel_helpers.c"
#include "_accel_simd_ops.c"
#include "_accel_accum_types.c"
#include "_accel_accum_init.c"
#include "_accel_accum_ops.c"
#include "_accel_accum_eval.c"
#include "_accel_features.c"
#include "_accel_attacks.c"
#include "_accel_direct.c"
/* ---- Self-contained shogi C layer (position, movegen, make/unmake) ---- */
#include "_shogi_constants.c"
#include "_shogi_make_unmake.c"
#include "_shogi_movegen_c.c"
#include "_shogi_pyapi.c"
#include "_shogi_eval_c.c"
#include "_shogi_rule_search.c"
/* ---- Chess rule-based evaluator (C port of _chess_rule_based) ---- */
#include "_chess_eval_c.c"
/* ---- Chess C engine (constants, movegen, make/unmake, pyapi) ------ */
#include "_chess_constants.c"
#include "_chess_make_unmake.c"
#include "_chess_movegen_c.c"
#include "_chess_pyapi.c"
#include "_chess_rule_search.c"
/* ---- CSearch layer: types first, then helpers, then C-native search,
 *      then lifecycle + methods (which reference cnative methods). ---- */
#include "_csearch_types.c"
#include "_csearch_utils.c"
#include "_csearch_accum.c"
#include "_csearch_ordering.c"
#include "_csearch_qsearch.c"
#include "_csearch_alphabeta.c"
#include "_csearch_root.c"
#include "_csearch_cnative.c"
#include "_csearch_lifecycle.c"
#include "_csearch_methods.c"
#include "_accel_module.c"
